name: 'Get & Cache Dependencies'
description: 'An action to get and cache dependencies for NodeJS projects'
runs:
  using: 'composite' # must be composite
  steps:
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
        cache-dependency-path: web_app/package-lock.json

    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm # internal dependecies
        key: node-modules-${{ hashFiles('**/package-lock.json')}}

    - name: Install dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: npm ci # install dependencies from package-lock.json
      shell: bash